### ISSUE TITLE
Collab notebook error during Phyloio visualization

### ISSUE THREAD

**Issue by DVilutis** [DessimozLab/fold_tree#12]
![PhyloIO_error](https://github.com/DessimozLab/fold_tree/assets/89931120/78d1691a-c43e-48fc-924e-627684ec467f)

"Run Foldtree" and ""Plot Foldtree output" finish successfully, but the PhyloIO visualization fails due to id_mapper error (image attached).

**Comment by cactuskid** [comment]
I've successfully run the phylo io step today. can you tell me what input you used so I can replicate the error?
