### ISSUE TITLE
error running script: cannot execute foldseek binary file

### ISSUE THREAD

**Issue by ruthalee** [DessimozLab/fold_tree#14]
Hello, I am trying to run the script with a custom database. I get the error below.

`(foldtree) rulee@infra04-wg324 fold_tree % snakemake --cores 4 --use-conda -s workflow/fold_tree --config folder=decaheme custom_structs=True
/Users/ruthlee/fold_tree/
Config file /Users/ruthlee/fold_tree/workflow/config/config_vars.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                   count
------------------  -------
all                       1
foldseek2distmat          1
foldseek_allvall_1        1
mad_root_post             3
postprocess               3
quicktree                 3
total                    12

Select jobs to execute...

[Wed Jan 24 16:54:30 2024]
rule foldseek_allvall_1:
    input: decaheme/finalset.csv
    output: decaheme/allvall_1.csv
    log: decaheme/logs/foldseekallvall.log
    jobid: 7
    reason: Missing output files: decaheme/allvall_1.csv
    wildcards: folder=decaheme
    resources: tmpdir=/var/folders/c8/9q8d9t1x4yz69_zzdytq4bww0000gn/T

Activating conda environment: foldtree
/bin/bash: /Users/ruthlee/fold_tree/foldseek/foldseek: cannot execute binary file
[Wed Jan 24 16:54:30 2024]
Error in rule foldseek_allvall_1:
    jobid: 7
    input: decaheme/finalset.csv
    output: decaheme/allvall_1.csv
    log: decaheme/logs/foldseekallvall.log (check log file(s) for error details)
    conda-env: foldtree
    shell:
        /Users/ruthlee/fold_tree/foldseek/foldseek easy-search decaheme/structs/ decaheme/structs/ decaheme/allvall_1.csv decaheme/tmp --format-output 'query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,lddt,lddtfull,alntmscore' --exhaustive-search --alignment-type 2 -e inf --threads 1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-01-24T165429.787296.snakemake.log`

I followed the instructions for the installation. The only hiccup I had was with some bioconda dependencies. I have an M1 Mac, so I had force an osx-64 environment to configure the foldtree environment. I don't know if that would do anything. Any ideas?
Thank so much for your help!

**Comment by aamirrr-m** [comment]
I think i may have found a resolution for my linux vm installation: 

head to your **config_vars.yaml** file in fold_tree/workflow/config

find the line **foldseek_path: provided**

and replace **provided** with **foldseek** (all lowercase)

and try it again.

I had this issue starting from yesterday, let me know if it works for you too.

**Comment by cactuskid** [comment]
I've changed the configfile variable to default to just use the latest foldseek instead of the binary included in the repo ( I wanted my results to be replicable so I was using the same version throughout all my benchmarking experiments ). This shouldn't impact results though.

**Comment by ruthalee** [comment]
Thank you aamirr-m and cactuskid. I installed on my university's linux computing system and it ran perfectly. I'll try again on my mac with the new change, but I have something working regardless. Thank you!
