### ISSUE TITLE
Trying to run foldtree with custom structures but get a missing identifiers.txt error 

### ISSUE THREAD

**Issue by msleutel** [DessimozLab/fold_tree#21]
Trying to run foldtree with custom structures but get a missing identifiers.txt error ... ?

Command:
snakemake --cores 12 --use-conda -s /software/AMD/git/fold_tree/workflow/fold_tree --config folder=./myfam custom_structs=True

PBDs were placed in ./myfam/structs

Error:
Config file /software/AMD/git/fold_tree/workflow/config/config_vars.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Relative file path './myfam/plddt.json' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/foldtree_struct_tree.PP.nwk.rooted.final' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/alntmscore_struct_tree.PP.nwk.rooted.final' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/lddt_struct_tree.PP.nwk.rooted.final' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/finalset.csv' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/plddt.json' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/logs/plddt.log' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/sequence_dataset.csv' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/sequences.fst' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/finalset.csv' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/logs/dlstructs.log' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/identifiers.txt' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/sequence_dataset.csv' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Relative file path './myfam/logs/dlsequences.log' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
MissingInputException in rule dl_ids_sequences in file /software/AMD/git/fold_tree/workflow/fold_tree, line 105:
Missing input files for rule dl_ids_sequences:
    output: ./myfam/sequence_dataset.csv
    wildcards: folder=./myfam
    affected files:
        ./myfam/identifiers.txt

**Comment by cactuskid** [comment]
before running the piline can you ensure that you have an empty identifiers.txt file in the myfam directory and that all of the structures are placede inside a structs directory ( i.e. ./myfam/structs/ ). If the error persists it could be something else but I think this is the source of your problem.

**Comment by msleutel** [comment]
Solved!

**Comment by cactuskid** [comment]
great. happy treebuilding!
