### ISSUE TITLE
zip file of pdbs failed

### ISSUE THREAD

**Issue by jerryissilly** [DessimozLab/fold_tree#3]
[random-fun.zip](https://github.com/DessimozLab/fold_tree/files/12768256/random-fun.zip)

Dear Dev team

Looks like an awesome tool! When I am trying to run FoldTree (Colab) with this zip file containing some pdbs, it errored out at "step 4". Any insights about how to avoid this error? I attached my inputs for your troubleshoot reference.

Regards,
Jerry

Below is the error message:

[Fri Sep 29 15:21:55 2023]
Finished job 1.
4 of 15 steps (27%) done
Traceback (most recent call last):
  File "/content/.snakemake/scripts/tmpa1vcu59b.foldseekres2distmat_simple.py", line 9, in <module>
    res = pd.read_table(snakemake.input[0], header = None)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1282, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1723, in _make_engine
    return mapping[engine](f, **self.options)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 586, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[Fri Sep 29 15:21:55 2023]
Error in rule foldseek2distmat:
    jobid: 7
    input: ./test_40814_0/allvall_1.csv
    output: ./test_40814_0/foldtree_fastmemat.txt, ./test_40814_0/alntmscore_fastmemat.txt, ./test_40814_0/lddt_fastmemat.txt
    log: ./test_40814_0/logs/foldseek2distmat.log (check log file(s) for error details)
    conda-env: foldtree

RuleException:
CalledProcessError in file /content/fold_tree/workflow/fold_tree, line 90:
Command 'source /usr/local/bin/activate 'foldtree'; set -euo pipefail;  /usr/local/bin/python3.10 /content/.snakemake/scripts/tmpa1vcu59b.foldseekres2distmat_simple.py' returned non-zero exit status 1.
  File "/content/fold_tree/workflow/fold_tree", line 90, in __rule_foldseek2distmat
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-09-29T152146.850816.snakemake.log
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-6-4387aeaa2f49>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('bash', '-s $jobname $input_type', 'JOBNAME=$1\nINPUT_TYPE=$2\nSUFFIX=""\nif [[ $INPUT_TYPE = "custom" ]]; then\n  mkdir -p "${JOBNAME}/structs"\n  mv "${JOBNAME}/"*.pdb "${JOBNAME}/"*.cif "${JOBNAME}/structs"\n  SUFFIX="custom_structs=True"\nfi\nsnakemake --cores $(nproc --all) --use-conda -s fold_tree/workflow/fold_tree --config folder="./${JOBNAME}" filter=False $SUFFIX  #> /dev/null 2>&1\n#snakemake --cores 4 --use-conda -s fold_tree/workflow/fold_tree --config folder=./${jobname} filter=False\n')

4 frames
<decorator-gen-103> in shebang(self, line, cell)

[/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py](https://localhost:8080/#) in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'JOBNAME=$1\nINPUT_TYPE=$2\nSUFFIX=""\nif [[ $INPUT_TYPE = "custom" ]]; then\n  mkdir -p "${JOBNAME}/structs"\n  mv "${JOBNAME}/"*.pdb "${JOBNAME}/"*.cif "${JOBNAME}/structs"\n  SUFFIX="custom_structs=True"\nfi\nsnakemake --cores $(nproc --all) --use-conda -s fold_tree/workflow/fold_tree --config folder="./${JOBNAME}" filter=False $SUFFIX  #> /dev/null 2>&1\n#snakemake --cores 4 --use-conda -s fold_tree/workflow/fold_tree --config folder=./${jobname} filter=False\n'' returned non-zero exit status 1.

**Comment by martin-steinegger** [comment]
Could you please specify how you were running the colab?

**Comment by jerryissilly** [comment]
Sure!
I was using this link via twitter (https://colab.research.google.com/github/DessimozLab/fold_tree/blob/main/notebooks/Foldtree.ipynb)

Chose custom at the first step, upload the attached zip file, and then "Runtime" -> "Run all"
<img width="883" alt="image" src="https://github.com/DessimozLab/fold_tree/assets/146461924/7aa0789c-0489-439d-aeb5-8bf9ad21c1c1">

**Comment by cactuskid** [comment]
I took a look at your zip file. Could it be that you have a directory structure inside of it instead of a file containing just pdbs?

**Comment by cactuskid** [comment]
I've changed this part of the collab notebook to generate the proper folder structure. hopefully it will work for you now. sorry about this issue.
