### ISSUE TITLE
Issue with running the script

### ISSUE THREAD

**Issue by garima-setia** [DessimozLab/fold_tree#4]
I am trying to run this command "snakemake --cores 1 --use-conda -s workflow/fold_tree --config folder=myfam filter=False" but it is giving me an error. Looks like there is an issue with the script. 

The error message:
(foldtree) [gsetia@turing fold_tree]$ snakemake --cores 1 --use-conda -s workflow/fold_tree --config folder=myfam filter=False
/home/gsetia/fold_tree/
Config file /home/gsetia/fold_tree/workflow/config/config_vars.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                   count
------------------  -------
all                       1
foldseek2distmat          1
foldseek_allvall_1        1
mad_root_post             3
postprocess               3
quicktree                 3
total                    12

Select jobs to execute...

[Fri Sep 29 14:08:12 2023]
rule foldseek_allvall_1:
    input: myfam/finalset.csv
    output: myfam/allvall_1.csv
    log: myfam/logs/foldseekallvall.log
    jobid: 8
    reason: Missing output files: myfam/allvall_1.csv
    wildcards: folder=myfam
    resources: tmpdir=/tmp

Activating conda environment: foldtree
/usr/bin/bash: line 1:  1542 Illegal instruction     (core dumped) /home/gsetia/fold_tree/foldseek/foldseek easy-search myfam/structs/ myfam/structs/ myfam/allvall_1.csv myfam/tmp --format-output 'query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,lddt,lddtfull,alntmscore' --exhaustive-search --alignment-type 2 -e inf
[Fri Sep 29 14:08:14 2023]
Error in rule foldseek_allvall_1:
    jobid: 8
    input: myfam/finalset.csv
    output: myfam/allvall_1.csv
    log: myfam/logs/foldseekallvall.log (check log file(s) for error details)
    conda-env: foldtree
    shell:
        /home/gsetia/fold_tree/foldseek/foldseek easy-search myfam/structs/ myfam/structs/ myfam/allvall_1.csv myfam/tmp --format-output 'query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,lddt,lddtfull,alntmscore' --exhaustive-search --alignment-type 2 -e inf
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-09-29T140812.273556.snakemake.log
(foldtree) [gsetia@turing fold_tree]$

**Comment by OlafKranse** [comment]
Cloning the git again fixed this issue for me

**Comment by cactuskid** [comment]
is this still an issue @garima-setia ? Have you gotten everything to work?

**Comment by garima-setia** [comment]
Hi @cactuskid yes it worked now.
