### ISSUE TITLE
How to specify number of threads?

### ISSUE THREAD

**Issue by linda5mith** [DessimozLab/fold_tree#5]
Hi I'm just wondering is it possible to specify the number of threads? Many thanks!

**Comment by cactuskid** [comment]
Hey Linda. Thanks for the comment. I've added a command line flag for the fold_tree workflow for this. The readme is updated with an example of how to use this flag. Hope this helps

**Comment by linda5mith** [comment]
Hi, sorry only seeing this now! Brilliant thank you very much! :)
