### ISSUE TITLE
error using custom dataset

### ISSUE THREAD

**Issue by james-rs-bio** [DessimozLab/fold_tree#6]
Hello,

I gave Foldtree a try on Google Colab using a zipped folder containing pdb files and the "custom" option.  Unfortunately I got this error message following step 3:

`CalledProcessError: Command 'b'JOBNAME=$1\nINPUT_TYPE=$2\nSUFFIX=""\nif [[ $INPUT_TYPE = "custom" ]]; then\n  mkdir -p "${JOBNAME}/structs"\n  mv "${JOBNAME}/"*.pdb "${JOBNAME}/"*.cif "${JOBNAME}/structs"\n  SUFFIX="custom_structs=True"\nfi\nsnakemake --cores $(nproc --all) --use-conda -s fold_tree/workflow/fold_tree --config folder="./${JOBNAME}" filter=False $SUFFIX  #> /dev/null 2>&1\n#snakemake --cores 4 --use-conda -s fold_tree/workflow/fold_tree --config folder=./${jobname} filter=False\n'' returned non-zero exit status 1.`

Best regards,
Jim

**Comment by liaojing1111** [comment]
I encountered the same issue when running the 'custom' option in Colab. Looking forward to resolving this problem.

**Comment by hirenj** [comment]
I kind of managed to get it working by putting the custom PDBs into a structs folder, which is a subfolder of the generated job folder. Also, I had to make sure that the identifiers.txt file was present, and empty.

**Comment by cactuskid** [comment]
thanks for bringing this to our attention. I fiddled with the notebook a bit to grab the structures and put them in a folder with the right name. hopefully this helps. let me know if it works now

**Comment by hirenj** [comment]
Just tried it out, and it works well! A nice-to-have would be if it didn't bail when it hit bad PDB files, and just ignored the bad PDB files, but I think that's more my problem than your problem to solve!
