### ISSUE TITLE
Astral workflow

### ISSUE THREAD

**Issue by aamirrr-m** [DessimozLab/fold_tree#9]
Hello I was wondering if the astral workflow is working? I have tried to run it multiple times but I have had no success. This is what I have tried:

snakemake --cores 4 --use-conda -s ./workflow/Astral --config folder=./Results

But also using astral from its github 

java -jar [path/to/astral] -i file.tree -o file.tre

I can produce the trees using the fold_tree workflow. Just not this one. Thank you for your help in advance

**Comment by cactuskid** [comment]
Hi, No this one is still under development and not working. I wouldn't use it yet.

**Comment by aamirrr-m** [comment]
Ah no worries, thank you for the response.
